train:
  seed: 1
  torch_deterministic: True
  device: cuda
  total_timesteps: 10_000_000
  learning_rate: 2.5e-4
  num_steps: 90
  anneal_lr: True
  gamma: 0.99
  gae_lambda: 0.95
  num_minibatches: 4
  update_epochs: 4
  norm_adv: True
  clip_coef: 0.1
  clip_vloss: True
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  target_kl: ~

  num_envs: 8
  envs_per_worker: 1
  envs_per_batch: ~
  env_pool: True
  verbose: True
  data_dir: experiments
  checkpoint_interval: 200
  pool_kernel: [0]
  batch_size: 8192
  batch_rows: 2048
  bptt_horizon: 1 #8
  vf_clip_coef: 0.1
  compile: False
  compile_mode: reduce-overhead

  action_space_type: discrete
  
reward_params:
  rewardType: OnGoalAchieved  
  distanceToGoalThreshold: 3.0
  distanceToExpertThreshold: 50.0

parameters:
  polylineReductionThreshold: 1.0
  observationRadius: 1000.0
  datasetInitOptions: FirstN
  collisionBehaviour: Ignore
  maxNumControlledVehicles: 1
  rewardParams: reward_params

sim_manager:
  exec_mode: CUDA
  gpu_id: 0
  num_worlds: 1
  auto_reset: false
  json_path: /home/aarav/gpudrive/nocturne_data/
  enable_batch_renderer: false